name: unit tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        always-auth: true
        registry-url: 'https://registry.npmjs.org'
    - name: build
      run: |
        yarn
        yarn build
    - name: test
      run: |
        yarn link
        yarn link schematic-fp
        yarn test
    - name: publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name $GITHUB_ACTOR
        git config user.email ${GITHUB_ACTOR}@github.com
        yarn version --patch
        git push --tags
        yarn publish
